#!/usr/bin/env python
#
# Copyright (c) 2023 Samsung Electronics Co., Ltd All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from importlib import import_module


def test_import(module_name):
    print(module_name)

    try:
        module = import_module(module_name)
        print(module)
        print('Success!')

    except ImportError as e:
        print(e)


if __name__ == "__main__":
    sys.path.append('/usr/local/lib/ovi/plugins')

    if len(sys.argv) != 2:
        print('Usage:\n  ./py_import_tester {module_name}')
        exit(2)

    test_import(sys.argv[1])
